# Generated by Django 4.0.4 on 2023-01-07 16:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('drama_datas', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='dramadata',
            name='company',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='drama_datas.company', verbose_name='制作会社'),
        ),
        migrations.AlterField(
            model_name='dramadata',
            name='year',
            field=models.IntegerField(default=2021, verbose_name='放送年'),
        ),
    ]
