# Generated by Django 4.0.4 on 2023-01-07 16:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('drama_datas', '0002_dramadata_company_alter_dramadata_year'),
    ]

    operations = [
        migrations.AlterField(
            model_name='actor',
            name='birthday',
            field=models.DateField(blank=True, verbose_name='生年月日'),
        ),
        migrations.AlterField(
            model_name='actor',
            name='country',
            field=models.CharField(blank=True, max_length=128, verbose_name='出身地'),
        ),
        migrations.AlterField(
            model_name='actor',
            name='sex',
            field=models.IntegerField(blank=True, verbose_name='性別'),
        ),
    ]
