# Generated by Django 4.0.4 on 2023-01-07 16:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('drama_datas', '0003_alter_actor_birthday_alter_actor_country_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='actor',
            name='sex',
        ),
    ]
