# Generated by Django 4.0.4 on 2023-01-07 16:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('drama_datas', '0005_actor_sex'),
    ]

    operations = [
        migrations.AlterField(
            model_name='actor',
            name='sex',
            field=models.IntegerField(blank=True, choices=[(1, '男'), (2, '女'), (3, 'その他')], default=1, verbose_name='性別'),
        ),
    ]
