# Generated by Django 4.0.4 on 2023-01-07 16:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('drama_datas', '0006_alter_actor_sex'),
    ]

    operations = [
        migrations.AlterField(
            model_name='company',
            name='country',
            field=models.CharField(blank=True, max_length=128, verbose_name='国名'),
        ),
    ]
