# Generated by Django 4.0.4 on 2023-01-07 16:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('drama_datas', '0007_alter_company_country'),
    ]

    operations = [
        migrations.AddField(
            model_name='dramadata',
            name='patern',
            field=models.IntegerField(blank=True, choices=[(1, '連続'), (2, '単発')], default=1, verbose_name='区分'),
        ),
        migrations.CreateModel(
            name='Cast',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.IntegerField(choices=[(1, '主演'), (2, 'レギュラー'), (3, '友情出演'), (4, '特別出演'), (5, 'ゲスト出演'), (6, 'カメオ出演')], default=1, verbose_name='役区分')),
                ('name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='drama_datas.actor', verbose_name='氏名')),
                ('title', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='drama_datas.dramadata', verbose_name='出演作')),
            ],
        ),
    ]
