# Generated by Django 4.0.4 on 2023-01-20 16:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('drama_datas', '0009_actor_created_at_actor_created_by_actor_updated_at_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='actor',
            name='birthday',
            field=models.DateField(blank=True, null=True, verbose_name='生年月日'),
        ),
    ]
